### ISSUE TITLE
Augeas issues getting module to work

### ISSUE THREAD

**Issue by ghoneycutt** [camptocamp/puppet-varnish#30]
I am using Puppet v3.8.3 on EL6 with augeasproviders_core 2.1.2 and augeasproviders_shellvar 2.2.0 and am unable to get this module to work. I'm setting multi_instances to false.

Any pointers would be greatly appreciated.

```shell
# rpm -qa |grep aug
augeas-1.0.0-10.el6.x86_64
ruby-augeas-0.4.1-3.el6.x86_64
augeas-libs-1.0.0-10.el6.x86_64
```

```
Error: /Stage[main]/Varnish::Config/Varnish_param[storage]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[listen_address]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[secret_file]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[ttl]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[user]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[vcl_conf]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[admin_listen_address]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[listen_port]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[admin_listen_port]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
Error: /Stage[main]/Varnish::Config/Varnish_param[group]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:96, character:11)
```

**Comment by raphink** [comment]
What do you have on line 96 of your `/etc/sysconfig/varnish`?

**Comment by ghoneycutt** [comment]
Changed from varnish v2 to v3 and the error just moved a couple of lines

```
Error: /Stage[main]/Varnish::Config/Varnish_param[storage]: Could not evaluate: Augeas didn't load /etc/sysconfig/varnish with Shellvars.lns from /var/lib/puppet/lib/augeas/lenses: Syntax error (line:99, character:11)
```
The sysconfig file is stock from the package

https://gist.github.com/ghoneycutt/2dce6364fd313535705c#file-el6-sysconfig-varnish-L6-L99

**Comment by raphink** [comment]
OK, so it seems to have a hard time with continued quoted variables. From what I can tell, this was fixed in Augeas 1.2.0 with https://github.com/hercules-team/augeas/commit/d26208334bf88b881dbd0796a09acb23fce8d302

**Comment by ghoneycutt** [comment]
@raphink Thank you!!

Any pointers on finding a newer package? The docs at augeas.net say to check out EPEL though I don't see them there https://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/letter_a.group.html or at yum.puppetlabs.com

**Comment by raphink** [comment]
@domcleal usually knows where to find these :smile:

**Comment by domcleal** [comment]
Ah, that doc's old then - it was in EPEL5, but it's in (RH)EL itself in versions 6 and 7.  For 6, it won't be rebased beyond 1.1.0, but you could file a Bugzilla for the specific bug and we ought to backport that fix.

To get newer packages, you'd need to rebuild one for EL6 as 1.1.0's the latest.  There's a 1.4.0 preview SRPM for EL7, which you can get here: http://people.redhat.com/~dcleal/augeas-el7.2-preview/augeas-1.4.0-0.1.preview.el7.centos.src.rpm

Or you could get one from Fedora: http://koji.fedoraproject.org/koji/packageinfo?packageID=6131

Then rebuild with `mock -r epel-6-x86_64 *.src.rpm` or rpmbuild on an EL6 box.
